## matrices as ndarray objects

In [6]:
import numpy as np
y=np.array([44,21,37])
print(y)
print(y.shape)

[44 21 37]
(3,)


In [3]:
x=np.array([[1.2,1,545,1],[3.4,0,345,2],[3.2,1,754,3]])
print(x)
print(x.shape)

[[  1.2   1.  545.    1. ]
 [  3.4   0.  345.    2. ]
 [  3.2   1.  754.    3. ]]
(3, 4)


notice use of reshape

In [9]:
x=np.array([1.2,1,545,1,3.4,0,345,2,3.2,1,754,3]).reshape(3,4)
print(x)


[[  1.2   1.  545.    1. ]
 [  3.4   0.  345.    2. ]
 [  3.2   1.  754.    3. ]]


In [4]:
z=np.array([[1],[2],[3]])
print(z)
print(z.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [12]:
a=np.array([[1,1],[1,0]])
b=np.array([[1,0],[0,1]])
print(a-b)
print(-2*a)

[[ 0  1]
 [ 1 -1]]
[[-2 -2]
 [-2  0]]


In [13]:
print(np.dot(a,b))

[[1 1]
 [1 0]]


notice below that python understands that c is a vector, so aXc returns a vector instead of a 2X1 matrix

In [15]:
c=np.array([3,-2])
print(np.dot(a,c))

[1 3]
